config/routes.rb
Rails.application.routes.draw do

    root 'users#index', as: :users


    # get "/users" => "users#index", as: :users
    get 'users/new' => 'users#new', as: :new_user
    get '/users/:id' => 'users#show', as: :user_letters 

    post '/' => 'users#create'

    get 'sessions/new' => 'sessions#new', as: :new_session
    
    post 'sessions/new' => 'sessions#create', as: :create_session
    
    get 'sessions/destroy' => 'sessions#destroy', as: :destroy_session

    get 'targets/' => 'targets#index', as: :targets

    get "letters/" => "letters#index", as: :letters

    get "letters/new" => "letters#new", as: :new_letter

    post "letters/" => "letters#create"

    get "letters/:id" => "letters#show", as: :letter

    get "letters/:id/edit" => "letters#edit", as: :edit_letter

    patch "letters/:id" => "letters#update"

    delete "letters/:id" => "letters#destroy"
end

app/models/letter.rb
class Letter < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :letters

  validates :email, presence: true, uniqueness: { case_sensitive: false}, length: { in: 5..50 }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i ,
    message: "enter valid email address" }

  validates :password, presence: true, length: { in: 6..30 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user

protected  
  #this is where we create a method that returns a logged in user. 
  #This method will at first attempt to return the current user,
  #this is the @user part. The || says: OR if the @user doesn't exist, assign the result of User.find...
  #to @user, BUT, only attempt the User.find if there is a :user_id stored in the session. 
  def current_user
    @current_user ||= User.find session[:user_id]  if session[:user_id] 
  end  

  def authorize
      unless current_user
        flash[:error] = "you must sign in first to go to that page"
        redirect_to new_session_path
      end
  end

end

app/controllers/letters_controller.rb
class LettersController < ApplicationController

	def index
		@letters = Letter.all
	end

	def show
  		@letter = Letter.find(params[:id])
	end

	def new 
		@letters = Letter.new
	end

	def create
  		@letters = Letter.new(letter_params)
  		respond_to do |format|
  		if current_user.letters.push @letters
	       format.html { redirect_to user_letters_path(current_user), notice: 'Post was successfully created.' }
	       format.json { render :show, status: :created, location: @letters }

     	else
	       format.html { render :new }
	       format.json { render json: @user.errors, status: :unprocessable_entity }
     	end
 	end
  		# if @letter.save
    # 		redirect_to letters_path
  		# else
    # 		render :new
  		# end
	end

	def edit
  		@letter = Letter.find(params[:id])
	end

	def update
  		@letter = Letter.find(params[:id])

  		if @letter.update_attributes(letter_params)
    		redirect_to user_letters_path(current_user)
  		else
    		render :edit
  		end
	end

	def destroy
  		@letter = Letter.find(params[:id])
  		@letter.destroy
  		redirect_to user_letters_path(current_user)
	end


	private
		def letter_params
  		params.require(:letter).permit(:reciever, :title, :content)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

 #return a new user for our form inside the 'new' view
  def new
      @user = User.new
  end

  def create
        user = User.where( email: user_params[:email]).first

        if user && user.authenticate(user_params[:password])
          session[:user_id] = user.id

          flash[:success] = 'You are signed in!'
          redirect_to user_letters_path(current_user)
        else
          #redirect back to the page
          flash[:error] = 'unable to sign you in'

          redirect_to new_session_path
        end
    end

    def destroy
      session[:user_id] = nil
      flash[:error] = 'you have been logged out'
      redirect_to users_path
    end


private

    def user_params
      params.require(:user).permit(:email,:password)
    end




end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController

	before_action :authorize   

	def index

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  #return a view named 'new' that will be used to register a new user
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @letters = @user.letters
  end

  def create
      user = User.new(user_params)
      if user.save
        #redicret to signed in
        flash[:success] = 'you are registered'
        redirect_to new_session_path
      else

        flash[:error] = 'registration has failed'

        redirect_to new_user_path

      end
  end

  private

  def user_params
    params.require(:user).permit(:email,:password,:password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snail Mail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
</head>
<body class="container-fluid">

<%= yield %>

</body>
</html>

app/views/letters/edit.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/ ">
        <img alt="Home" id="logo" src="http://www.iconhot.com/icon/png/devine-icons-part-2/256/mail-2-w.png">
      </a>

      <div class="btn btn-default" id="viewlet">
        <% if current_user  %>
          <%= link_to "View Letters", user_letters_path(current_user) %>
        <% else %>
          <%= link_to "View Letters", new_session_path %>
        <% end %>
      </div>

      <div class="btn btn-default" id="compose">
        <% if current_user  %>
          <%= link_to "Compose", new_letter_path %>
        <% else %>
          <%= link_to "Compose", new_session_path %>
        <% end %>
      </div>

      <div class="btn btn-default" id="login">
        <% if current_user  %>
          <%= link_to "Logout", destroy_session_path %>
        <% else %>
          <%= link_to "Login", new_session_path %>
        <% end %>
      </div>
      
      <p class="navbar-text" id="navtext">
        <% if current_user  %>You are signed in as <%= current_user.email %></p> 
        <% else %>You are not signed in<% end %>
      </p>

    
    </div>
  </div>
</nav>

<h1>Edit this Letter!</h1>

<%= form_for @letter do |f| %>

    <div class="form-group">
        <%= f.label :recipient %>
        <%= f.text_field :reciever, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group form-group-xlg">
        <%= f.label :content %>
        <%= f.text_area :content, class: "form-control" %>
    </div>

    <div class="btn btn-default">
        <%= f.submit "Save These Changes" %>
    </div>

<% end %>

app/views/letters/index.html.erb
<head>
<script src='http://my.mobfox.com/ad.js'></script>
</head>



<body>
<h1>Giant Mail Bag</h1>

<%= link_to "Compose a new Letter", new_letter_path  %>

<ul>
    <% @letters.each do |letter| %>
        <li>
            <strong> <%= letter.title %> </strong> 
            <%= link_to "Open this Letter", letter_path(letter) %>
        </li>
    <% end %>
   
</ul>



<script>
RequestAd_({

    // Ad Request Variables
    s:'2db389dcebf57cbdf1784f608b987292',
    m:'live', <!-- Change to 'test' to show a test ad -->
    adspace_width:'600', <!-- Maximum Width of your Banner -->
    adspace_height:'200', <!-- Maximum Height of your Banner -->
    adspace_strict:'0', <!-- If you change this parameter to 1, the ad size set above will be strict and no smaller ads will be shown. -->
    backfillhtml:'', <!-- Insert HTML Code here that should be shown when no ad is available -->
    prependclickcontent:'', <!-- Prepend something before Click URLs. It is recommended to leave this parameter empty.  -->
    trackingpixelurl:'' <!-- Ping a Tracking Pixel everytime an ad is shown. -->
	});
</script>

</body>

app/views/letters/new.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/ ">
        <img alt="Home" id="logo" src="http://www.iconhot.com/icon/png/devine-icons-part-2/256/mail-2-w.png">
      </a>

      <div class="btn btn-default" id="viewlet">
        <% if current_user  %>
          <%= link_to "View Letters", user_letters_path(current_user) %>
        <% else %>
          <%= link_to "View Letters", new_session_path %>
        <% end %>
      </div>

      <div class="btn btn-default" id="compose">
        <% if current_user  %>
          <%= link_to "Compose", new_letter_path %>
        <% else %>
          <%= link_to "Compose", new_session_path %>
        <% end %>
      </div>

      <div class="btn btn-default" id="login">
        <% if current_user  %>
          <%= link_to "Logout", destroy_session_path %>
        <% else %>
          <%= link_to "Login", new_session_path %>
        <% end %>
      </div>
      
      <p class="navbar-text" id="navtext">
        <% if current_user  %>You are signed in as <%= current_user.email %></p> 
        <% else %>You are not signed in<% end %>
      </p>

    
    </div>
  </div>
</nav>

<h1>Compose a new letter</h1>

<%= form_for @letters do |f| %>

    <div class="form-group">
        <%= f.label :recipient %>
        <%= f.text_field :reciever, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group form-group-xlg">
        <%= f.label :content %>
        <%= f.text_area :content, class: "form-control" %>
    </div>

    <div class="btn btn-default">
    <%= f.submit "Save Letter" %>
    </div>
    

<% end %>

app/views/letters/show.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/ ">
        <img alt="Home" id="logo" src="http://www.iconhot.com/icon/png/devine-icons-part-2/256/mail-2-w.png">
      </a>

      <div class="btn btn-default" id="viewlet">
        <% if current_user  %>
          <%= link_to "View Letters", user_letters_path(current_user) %>
        <% else %>
          <%= link_to "View Letters", new_session_path %>
        <% end %>
      </div>

      <div class="btn btn-default" id="compose">
        <% if current_user  %>
          <%= link_to "Compose", new_letter_path %>
        <% else %>
          <%= link_to "Compose", new_session_path %>
        <% end %>
      </div>

      <div class="btn btn-default" id="login">
        <% if current_user  %>
          <%= link_to "Logout", destroy_session_path %>
        <% else %>
          <%= link_to "Login", new_session_path %>
        <% end %>
      </div>
      
      <p class="navbar-text" id="navtext">
        <% if current_user  %>You are signed in as <%= current_user.email %></p> 
        <% else %>You are not signed in<% end %>
      </p>

    
    </div>
  </div>
</nav>



<h2> To: <em><%= @letter.reciever %></em> </h2>
<h2> From: <em><%= @letter.user.email %></em> </h2>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @letter.title %></h3>
  </div>
  <div class="panel-body">
    <%= @letter.content %>
  </div>
</div>

<div class="btn btn-info">
	<%= link_to "Edit this Letter", edit_letter_path(@letter) %>
</div>

<div class="btn btn-info">
<%= link_to "Delete this Letter", letter_path, method: :delete, data: { confirm: "Are you sure you want to delete this letter permanently?"} %>
</div>

<div class="btn btn-success">
  <%= link_to "Send it off!", user_letters_path(current_user), data: {confirm: "App is currently in development. In the mean time, polish those communication skills."} %>
</div>

app/views/targets/index.html.erb
<div>Target Page</div>

app/views/users/index.html.erb
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/ ">
        <img alt="Home" id="logo" src="http://www.iconhot.com/icon/png/devine-icons-part-2/256/mail-2-w.png">
      </a>

      <div class="btn btn-default" id="viewlet">
        <% if current_user  %>
          <%= link_to "View Letters", user_letters_path(current_user) %>
        <% else %>
          <%= link_to "View Letters", new_session_path %>
        <% end %>
      </div>

      <div class="btn btn-default" id="compose">
        <% if current_user  %>
          <%= link_to "Compose", new_letter_path %>
        <% else %>
          <%= link_to "Compose", new_session_path %>
        <% end %>
      </div>

      <div class="btn btn-default" id="login">
        <% if current_user  %>
          <%= link_to "Logout", destroy_session_path %>
        <% else %>
          <%= link_to "Login", new_session_path %>
        <% end %>
      </div>
      
      <p class="navbar-text" id="navtext">
        <% if current_user  %>You are signed in as <%= current_user.email %></p> 
        <% else %>You are not signed in<% end %>
      </p>

    
    </div>
  </div>
</nav>


  <div class="page-header">
    <h1>Welcome to SnailMail <br> <small>Where we bring mail to the internet</small></h1>
  </div>


  <div class="btn btn-info" id="register">
    <% if current_user %> 
      <%= link_to "Get started writing", new_letter_path %>
    <% else %> 
      <%= link_to "Register Your Account", new_user_path %>
    <% end %>
  </div>


<% flash.each do |key,value|  %>
    <div class="<%= key %>" > <%= value %> </div>
<% end %>



</body>

app/views/users/new.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/ ">
        <img alt="Home" id="logo" src="http://www.iconhot.com/icon/png/devine-icons-part-2/256/mail-2-w.png">
      </a>
 
      <div class="btn btn-default" id="viewlet">
        <% if current_user  %>
          <%= link_to "View Letters", user_letters_path(current_user) %>
        <% else %>
          <%= link_to "View Letters", new_session_path %>
        <% end %>
      </div>

      <div class="btn btn-default" id="compose">
        <% if current_user  %>
          <%= link_to "Compose", new_letter_path %>
        <% else %>
          <%= link_to "Compose", new_session_path %>
        <% end %>
      </div>

      <div class="btn btn-default" id="login">
        <% if current_user  %>
          <%= link_to "Logout", destroy_session_path %>
        <% else %>
          <%= link_to "Login", new_session_path %>
        <% end %>
      </div>
      
      <p class="navbar-text" id="navtext">
        <% if current_user  %>You are signed in as <%= current_user.email %></p> 
        <% else %>You are not signed in<% end %>
      </p>

    
    </div>
  </div>
</nav>




<%= form_for(@user) do |f| %>

      <% flash.each do |key,value|  %>
        <div class="<%= key %>" > <%= value %> </div>
      <% end %>

      <h1>Register with SnailMail</h1>

      <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>

      <%= f.submit "Signup", class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/ ">
        <img alt="Home" id="logo" src="http://www.iconhot.com/icon/png/devine-icons-part-2/256/mail-2-w.png">
      </a>

      <div class="btn btn-default" id="viewlet">
        <% if current_user  %>
          <%= link_to "View Letters", user_letters_path(current_user) %>
        <% else %>
          <%= link_to "View Letters", new_session_path %>
        <% end %>
      </div>

      <div class="btn btn-default" id="compose">
        <% if current_user  %>
          <%= link_to "Compose", new_letter_path %>
        <% else %>
          <%= link_to "Compose", new_session_path %>
        <% end %>
      </div>

      <div class="btn btn-default" id="login">
        <% if current_user  %>
          <%= link_to "Logout", destroy_session_path %>
        <% else %>
          <%= link_to "Login", new_session_path %>
        <% end %>
      </div>
      
      <p class="navbar-text" id="navtext">
        <% if current_user  %>You are signed in as <%= current_user.email %></p> 
        <% else %>You are not signed in<% end %>
      </p>

    
    </div>
  </div>
</nav>



<div class="page-header">
    <h1>Your Letters <br> <small>Click Compose to get started</small></h1>
</div>


<div class="list-group">
  <ul>   
    <% @letters.each do |letter| %>
        <li class="list-group-item active">
            <strong> To: <%= letter.reciever %> </strong>
            <br>
            <strong> <%= letter.title %> </strong> 
            <%= link_to "Click to Review this Letter", letter_path(letter) %>
        </li>
    <% end %>
  </ul>
</div>



  